### ISSUE TITLE
Adding fonts for languages other than English

### ISSUE THREAD

**Issue by dora-su** [JuliaBerry/SenseHat.jl#10]
The current set of fonts available within this library is limited to English/Latin characters. Hence, I'd like to implement font shapes for other languages.

I'll begin by adding Greek characters.

**Comment by dora-su** [comment]
I've finished Greek, and while that is up for review, I'll be working on accented characters.

**Comment by aviks** [comment]
fixed by #13 and #14 . Thanks @dora-su
