### ISSUE TITLE
Parsing error due to omitted comma in line 391 (src/text.jl)

### ISSUE THREAD

**Issue by mdvsh** [JuliaBerry/SenseHat.jl#19]
## Source 
[Line 391](https://github.com/JuliaBerry/SenseHat.jl/blob/be0f87b10856987af5986fa974986b29f3d8ba2d/src/text.jl#L391) doesn't seem to have a comma at the end. This leads to a parsing error.

#17 seems to have caused this. 

I've fixed this.

**Comment by aviks** [comment]
Thanks. We should setup CI of some form.
